//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  site: Site;
  siteConnection: SiteConnection;
  project: Project;
  projectConnection: ProjectConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteFilter>;
};


export type QueryProjectArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjectConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectFilter>;
};

export type DocumentFilter = {
  site?: InputMaybe<SiteFilter>;
  project?: InputMaybe<ProjectFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Site | Project | Folder;

export type SiteActions = {
  __typename?: 'SiteActions';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
  primary?: Maybe<Scalars['Boolean']['output']>;
};

export type SiteStats = {
  __typename?: 'SiteStats';
  value?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type SiteSections = {
  __typename?: 'SiteSections';
  label?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type SiteLinks = {
  __typename?: 'SiteLinks';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type Site = Node & Document & {
  __typename?: 'Site';
  title: Scalars['String']['output'];
  eyebrow?: Maybe<Scalars['String']['output']>;
  headline: Scalars['String']['output'];
  lead?: Maybe<Scalars['String']['output']>;
  summary?: Maybe<Scalars['String']['output']>;
  actions?: Maybe<Array<Maybe<SiteActions>>>;
  stats?: Maybe<Array<Maybe<SiteStats>>>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  profile?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  sections?: Maybe<Array<Maybe<SiteSections>>>;
  links?: Maybe<Array<Maybe<SiteLinks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type SiteActionsFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
  primary?: InputMaybe<BooleanFilter>;
};

export type SiteStatsFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type SiteSectionsFilter = {
  label?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type SiteLinksFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type SiteFilter = {
  title?: InputMaybe<StringFilter>;
  eyebrow?: InputMaybe<StringFilter>;
  headline?: InputMaybe<StringFilter>;
  lead?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  actions?: InputMaybe<SiteActionsFilter>;
  stats?: InputMaybe<SiteStatsFilter>;
  tags?: InputMaybe<StringFilter>;
  profile?: InputMaybe<StringFilter>;
  sections?: InputMaybe<SiteSectionsFilter>;
  links?: InputMaybe<SiteLinksFilter>;
};

export type SiteConnectionEdges = {
  __typename?: 'SiteConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Site>;
};

export type SiteConnection = Connection & {
  __typename?: 'SiteConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteConnectionEdges>>>;
};

export type ProjectSkills = {
  __typename?: 'ProjectSkills';
  name?: Maybe<Scalars['String']['output']>;
  detail?: Maybe<Scalars['String']['output']>;
};

export type ProjectLinks = {
  __typename?: 'ProjectLinks';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type Project = Node & Document & {
  __typename?: 'Project';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  summary?: Maybe<Scalars['String']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  weight?: Maybe<Scalars['Float']['output']>;
  projectType?: Maybe<Scalars['String']['output']>;
  github?: Maybe<Scalars['String']['output']>;
  demo?: Maybe<Scalars['String']['output']>;
  technical?: Maybe<Scalars['String']['output']>;
  problem?: Maybe<Scalars['String']['output']>;
  solution?: Maybe<Scalars['String']['output']>;
  result?: Maybe<Scalars['String']['output']>;
  tech?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  architectureTitle?: Maybe<Scalars['String']['output']>;
  architectureSummary?: Maybe<Scalars['String']['output']>;
  architecture?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  skills?: Maybe<Array<Maybe<ProjectSkills>>>;
  links?: Maybe<Array<Maybe<ProjectLinks>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type ProjectSkillsFilter = {
  name?: InputMaybe<StringFilter>;
  detail?: InputMaybe<StringFilter>;
};

export type ProjectLinksFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ProjectFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  featured?: InputMaybe<BooleanFilter>;
  weight?: InputMaybe<NumberFilter>;
  projectType?: InputMaybe<StringFilter>;
  github?: InputMaybe<StringFilter>;
  demo?: InputMaybe<StringFilter>;
  technical?: InputMaybe<StringFilter>;
  problem?: InputMaybe<StringFilter>;
  solution?: InputMaybe<StringFilter>;
  result?: InputMaybe<StringFilter>;
  tech?: InputMaybe<StringFilter>;
  architectureTitle?: InputMaybe<StringFilter>;
  architectureSummary?: InputMaybe<StringFilter>;
  architecture?: InputMaybe<StringFilter>;
  skills?: InputMaybe<ProjectSkillsFilter>;
  links?: InputMaybe<ProjectLinksFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ProjectConnectionEdges = {
  __typename?: 'ProjectConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Project>;
};

export type ProjectConnection = Connection & {
  __typename?: 'ProjectConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProjectConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSite: Site;
  createSite: Site;
  updateProject: Project;
  createProject: Project;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};


export type MutationCreateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};


export type MutationUpdateProjectArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectMutation;
};


export type MutationCreateProjectArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectMutation;
};

export type DocumentUpdateMutation = {
  site?: InputMaybe<SiteMutation>;
  project?: InputMaybe<ProjectMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  site?: InputMaybe<SiteMutation>;
  project?: InputMaybe<ProjectMutation>;
};

export type SiteActionsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
  primary?: InputMaybe<Scalars['Boolean']['input']>;
};

export type SiteStatsMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSectionsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type SiteLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type SiteMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  headline?: InputMaybe<Scalars['String']['input']>;
  lead?: InputMaybe<Scalars['String']['input']>;
  summary?: InputMaybe<Scalars['String']['input']>;
  actions?: InputMaybe<Array<InputMaybe<SiteActionsMutation>>>;
  stats?: InputMaybe<Array<InputMaybe<SiteStatsMutation>>>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  profile?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  sections?: InputMaybe<Array<InputMaybe<SiteSectionsMutation>>>;
  links?: InputMaybe<Array<InputMaybe<SiteLinksMutation>>>;
};

export type ProjectSkillsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  detail?: InputMaybe<Scalars['String']['input']>;
};

export type ProjectLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type ProjectMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  summary?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  weight?: InputMaybe<Scalars['Float']['input']>;
  projectType?: InputMaybe<Scalars['String']['input']>;
  github?: InputMaybe<Scalars['String']['input']>;
  demo?: InputMaybe<Scalars['String']['input']>;
  technical?: InputMaybe<Scalars['String']['input']>;
  problem?: InputMaybe<Scalars['String']['input']>;
  solution?: InputMaybe<Scalars['String']['input']>;
  result?: InputMaybe<Scalars['String']['input']>;
  tech?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  architectureTitle?: InputMaybe<Scalars['String']['input']>;
  architectureSummary?: InputMaybe<Scalars['String']['input']>;
  architecture?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  skills?: InputMaybe<Array<InputMaybe<ProjectSkillsMutation>>>;
  links?: InputMaybe<Array<InputMaybe<ProjectLinksMutation>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type SitePartsFragment = { __typename: 'Site', title: string, eyebrow?: string | null, headline: string, lead?: string | null, summary?: string | null, tags?: Array<string | null> | null, profile?: Array<string | null> | null, actions?: Array<{ __typename: 'SiteActions', label?: string | null, href?: string | null, primary?: boolean | null } | null> | null, stats?: Array<{ __typename: 'SiteStats', value?: string | null, label?: string | null } | null> | null, sections?: Array<{ __typename: 'SiteSections', label?: string | null, title?: string | null, body?: string | null } | null> | null, links?: Array<{ __typename: 'SiteLinks', label?: string | null, href?: string | null } | null> | null };

export type ProjectPartsFragment = { __typename: 'Project', title: string, description?: string | null, summary?: string | null, featured?: boolean | null, weight?: number | null, projectType?: string | null, github?: string | null, demo?: string | null, technical?: string | null, problem?: string | null, solution?: string | null, result?: string | null, tech?: Array<string | null> | null, architectureTitle?: string | null, architectureSummary?: string | null, architecture?: Array<string | null> | null, body?: any | null, skills?: Array<{ __typename: 'ProjectSkills', name?: string | null, detail?: string | null } | null> | null, links?: Array<{ __typename: 'ProjectLinks', label?: string | null, href?: string | null } | null> | null };

export type SiteQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiteQuery = { __typename?: 'Query', site: { __typename: 'Site', id: string, title: string, eyebrow?: string | null, headline: string, lead?: string | null, summary?: string | null, tags?: Array<string | null> | null, profile?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, actions?: Array<{ __typename: 'SiteActions', label?: string | null, href?: string | null, primary?: boolean | null } | null> | null, stats?: Array<{ __typename: 'SiteStats', value?: string | null, label?: string | null } | null> | null, sections?: Array<{ __typename: 'SiteSections', label?: string | null, title?: string | null, body?: string | null } | null> | null, links?: Array<{ __typename: 'SiteLinks', label?: string | null, href?: string | null } | null> | null } };

export type SiteConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteFilter>;
}>;


export type SiteConnectionQuery = { __typename?: 'Query', siteConnection: { __typename?: 'SiteConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiteConnectionEdges', cursor: string, node?: { __typename: 'Site', id: string, title: string, eyebrow?: string | null, headline: string, lead?: string | null, summary?: string | null, tags?: Array<string | null> | null, profile?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, actions?: Array<{ __typename: 'SiteActions', label?: string | null, href?: string | null, primary?: boolean | null } | null> | null, stats?: Array<{ __typename: 'SiteStats', value?: string | null, label?: string | null } | null> | null, sections?: Array<{ __typename: 'SiteSections', label?: string | null, title?: string | null, body?: string | null } | null> | null, links?: Array<{ __typename: 'SiteLinks', label?: string | null, href?: string | null } | null> | null } | null } | null> | null } };

export type ProjectQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProjectQuery = { __typename?: 'Query', project: { __typename: 'Project', id: string, title: string, description?: string | null, summary?: string | null, featured?: boolean | null, weight?: number | null, projectType?: string | null, github?: string | null, demo?: string | null, technical?: string | null, problem?: string | null, solution?: string | null, result?: string | null, tech?: Array<string | null> | null, architectureTitle?: string | null, architectureSummary?: string | null, architecture?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, skills?: Array<{ __typename: 'ProjectSkills', name?: string | null, detail?: string | null } | null> | null, links?: Array<{ __typename: 'ProjectLinks', label?: string | null, href?: string | null } | null> | null } };

export type ProjectConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectFilter>;
}>;


export type ProjectConnectionQuery = { __typename?: 'Query', projectConnection: { __typename?: 'ProjectConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProjectConnectionEdges', cursor: string, node?: { __typename: 'Project', id: string, title: string, description?: string | null, summary?: string | null, featured?: boolean | null, weight?: number | null, projectType?: string | null, github?: string | null, demo?: string | null, technical?: string | null, problem?: string | null, solution?: string | null, result?: string | null, tech?: Array<string | null> | null, architectureTitle?: string | null, architectureSummary?: string | null, architecture?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, skills?: Array<{ __typename: 'ProjectSkills', name?: string | null, detail?: string | null } | null> | null, links?: Array<{ __typename: 'ProjectLinks', label?: string | null, href?: string | null } | null> | null } | null } | null> | null } };

export const SitePartsFragmentDoc = gql`
    fragment SiteParts on Site {
  __typename
  title
  eyebrow
  headline
  lead
  summary
  actions {
    __typename
    label
    href
    primary
  }
  stats {
    __typename
    value
    label
  }
  tags
  profile
  sections {
    __typename
    label
    title
    body
  }
  links {
    __typename
    label
    href
  }
}
    `;
export const ProjectPartsFragmentDoc = gql`
    fragment ProjectParts on Project {
  __typename
  title
  description
  summary
  featured
  weight
  projectType
  github
  demo
  technical
  problem
  solution
  result
  tech
  architectureTitle
  architectureSummary
  architecture
  skills {
    __typename
    name
    detail
  }
  links {
    __typename
    label
    href
  }
  body
}
    `;
export const SiteDocument = gql`
    query site($relativePath: String!) {
  site(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteParts
  }
}
    ${SitePartsFragmentDoc}`;
export const SiteConnectionDocument = gql`
    query siteConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteFilter) {
  siteConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteParts
      }
    }
  }
}
    ${SitePartsFragmentDoc}`;
export const ProjectDocument = gql`
    query project($relativePath: String!) {
  project(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProjectParts
  }
}
    ${ProjectPartsFragmentDoc}`;
export const ProjectConnectionDocument = gql`
    query projectConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProjectFilter) {
  projectConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProjectParts
      }
    }
  }
}
    ${ProjectPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      site(variables: SiteQueryVariables, options?: C): Promise<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}> {
        return requester<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}, SiteQueryVariables>(SiteDocument, variables, options);
      },
    siteConnection(variables?: SiteConnectionQueryVariables, options?: C): Promise<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}> {
        return requester<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}, SiteConnectionQueryVariables>(SiteConnectionDocument, variables, options);
      },
    project(variables: ProjectQueryVariables, options?: C): Promise<{data: ProjectQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectQueryVariables, query: string}> {
        return requester<{data: ProjectQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectQueryVariables, query: string}, ProjectQueryVariables>(ProjectDocument, variables, options);
      },
    projectConnection(variables?: ProjectConnectionQueryVariables, options?: C): Promise<{data: ProjectConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectConnectionQueryVariables, query: string}> {
        return requester<{data: ProjectConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectConnectionQueryVariables, query: string}, ProjectConnectionQueryVariables>(ProjectConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  